name = "youshark-app"
compatibility_date = "2024-01-01"
pages_build_output_dir = "out"

[env.production]
name = "youshark-app"
compatibility_date = "2024-01-01"

[vars]
NODE_ENV = "production"

# Add your environment variables here
# WOOCOMMERCE_URL = "your-woocommerce-url"
# WOOCOMMERCE_KEY = "your-consumer-key"
# WOOCOMMERCE_SECRET = "your-consumer-secret"
# PAYPAL_CLIENT_ID = "your-paypal-client-id"
# PAYPAL_CLIENT_SECRET = "your-paypal-client-secret"
# JWT_SECRET = "your-jwt-secret"

# Uncomment and configure these for production
# [[env.production.kv_namespaces]]
# binding = "YOUSHARK_KV"
# id = "your-kv-namespace-id"

# [[env.production.d1_databases]]
# binding = "DB"
# database_name = "youshark-db"
# database_id = "your-database-id"